Repository ironcore-dev/ceph-provider, pull requests merged in 2023-11, with the labels that each got.

#392 Improve logging in gRPC server methods
  ori/bucket/server/bucket.go
  ori/bucket/server/bucket_create.go
  ori/bucket/server/bucket_delete.go
  ori/bucket/server/bucket_list.go
  ori/volume/server/status.go
  ori/volume/server/volume.go
  ori/volume/server/volume_create.go
  ori/volume/server/volume_delete.go
  ori/volume/server/volume_expand.go
  ori/volume/server/volume_list.go
Labels: enhancement, size/M

#408 Add breaking change rule to release drafter configuration
  .github/release-drafter.yml
Labels: size/XS, chore

#407 Switch to `ironcore-dev/controller-utils`
  go.mod
  go.sum
  iri/bucket/apiutils/apiutils.go
  iri/bucket/cmd/bucket/app/app.go
  iri/bucket/server/suite_test.go
  iri/volume/apiutils/apiutils.go
Labels: size/S, chore, integration-tests

#410 Fix links after project rename
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  mkdocs.yml
Labels: bug, documentation, size/XS, chore

#411 Change documentation title
  mkdocs.yml
Labels: size/XS, chore, integration-tests

#412 Update README and project housekeeping
  .reuse/dep5
  PROJECT
  README.md
Labels: documentation, size/M, chore

#415 Switch to `ironcore-image`
  README.md
  go.mod
  go.sum
  iri/volume/cmd/volume/app/app.go
  iri/volume/server/status.go
  pkg/api/snapshot.go
  pkg/controllers/image_controller.go
  pkg/controllers/snapshot_controller.go
  pkg/omap/config.go
Labels: documentation, enhancement, size/M, breaking
