Repository ironcore-dev/ceph-provider, pull requests merged in 2023-10, with the labels that each got.

#365 Add tests for `CreateBucket`
  go.mod
  go.sum
  ori/bucket/server/bucket_create_test.go
  ori/bucket/server/suite_test.go
  pkg/controllers/image_controller.go
Labels: enhancement, size/L

#374 Add test for ListBuckets
  ori/bucket/server/bucket_list_test.go
Labels: size/L

#375 Add tests for `DeleteBucket`
  ori/bucket/server/bucket_delete_test.go
Labels: size/L

#382 Refactor `Bucket` and `Volume` server, fix failing `Bucket` integration tests & bump deps
  .github/workflows/golangci-lint.yml
  .github/workflows/integration-test.yml
  .github/workflows/publish-docker.yml
  Makefile
  config/cephlet-bucket/cephlet-rbac/role.yaml
  go.mod
  go.sum
  integration/integration_suite_test.go
  integration/volume_create_integration_test.go
  integration/volume_delete_integration_test.go
  integration/volume_expand_integration_test.go
  integration/volume_list_integration_test.go
  integration/volume_status_integration_test.go
  ori/bucket/server/bucket.go
  ori/bucket/server/bucket_create.go
  ori/bucket/server/bucket_create_test.go
  ori/bucket/server/bucket_delete.go
  ori/bucket/server/bucket_delete_test.go
  ori/bucket/server/bucket_list.go
  ori/bucket/server/bucket_list_test.go
  ori/bucket/server/suite_test.go
  ori/volume/server/volume.go
  ori/volume/server/volume_create.go
  ori/volume/server/volume_delete.go
  ori/volume/server/volume_expand.go
  pkg/controllers/image_controller.go
  pkg/controllers/snapshot_controller.go
  pkg/utils/utils.go
Labels: bug, enhancement, size/XL, integration-tests, ok-to-image

#385 Fix sporadics in `Bucket` tests
  integration/integration_suite_test.go
  integration/volume_create_integration_test.go
  integration/volume_delete_integration_test.go
  integration/volume_expand_integration_test.go
  integration/volume_list_integration_test.go
  integration/volume_status_integration_test.go
  ori/bucket/apiutils/apiutils.go
  ori/bucket/apiutils/constants.go
  ori/bucket/server/bucket.go
  ori/bucket/server/bucket_create.go
  ori/bucket/server/bucket_create_test.go
  ori/bucket/server/bucket_delete.go
  ori/bucket/server/bucket_delete_test.go
  ori/bucket/server/bucket_list.go
  ori/bucket/server/bucket_list_test.go
  ori/bucket/server/bucketclass_list.go
  ori/bucket/server/server.go
  ori/bucket/server/suite_test.go
  ori/volume/apiutils/apiutils.go
  ori/volume/apiutils/constants.go
  ori/volume/server/volume_create.go
  ori/volume/server/volume_list.go
Labels: bug, size/L, integration-tests

#381 Add tests for `ListBucketClass`
  ori/bucket/server/bucket_create_test.go
  ori/bucket/server/bucket_delete_test.go
  ori/bucket/server/bucket_list_test.go
  ori/bucket/server/bucketclass_list_test.go
  ori/bucket/server/suite_test.go
Labels: enhancement, size/L, integration-tests
