Repository ironcore-dev/ceph-provider, pull requests merged in 2024-05, with the labels that each got.

#536 Bumped dependencies
  .github/workflows/golangci-lint.yml
  .github/workflows/size-label.yml
  Dockerfile
  go.mod
  go.sum
Labels: integration-tests

#527 Harmonized dockerfile target
  Dockerfile
Labels: size/XS

#540 Added `ResourceVersion`
  api/api.go
  internal/omap/omap.go
Labels: size/S, integration-tests
