Repository ironcore-dev/ceph-provider, pull requests merged in 2024-04, with the labels that each got.

#498 Bump golang to 1.22.1
  .github/workflows/golangci-lint.yml
  Makefile
  go.mod
Labels: size/XS, chore, integration-tests

#506 Remove the usage of `Ticker` for resyncing
  go.mod
  internal/controllers/image_controller.go
  internal/controllers/snapshot_controller.go
  internal/event/event.go
Labels: enhancement, size/XS, integration-tests

#507 Fix `deletionTimestamp` update if existing
  internal/omap/omap.go
Labels: bug, size/XS, integration-tests
