Repository ironcore-dev/ceph-provider, pull requests merged in 2024-08, with the labels that each got.

#574 Fix `Dockerfile` warnings
  Dockerfile
Labels: size/M, integration-tests

#570 Implement ListEvents Runtime Interface to Support Cross-Cluster Events
  cmd/volumeprovider/app/app.go
  go.mod
  go.sum
  internal/controllers/image_controller.go
  internal/event/recorder/event_recorder.go
  internal/event/recorder/event_recorder_test.go
  internal/volumeserver/event_list.go
  internal/volumeserver/server.go
Labels: enhancement, size/L

#582 Fixed integration test
  tests/integration/integration_suite_test.go
Labels: bug, size/XS, integration-tests

#581 Add placeholder ListEvents implementation for bucket operations
  go.mod
  go.sum
  internal/bucketserver/event_list.go
Labels: enhancement, size/M, integration-tests
